# Stack's standard Travis config, taken from
# http://docs.haskellstack.org/en/stable/GUIDE.html#travis-with-caching

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: generic

# GHC depends on GMP. You can add other dependencies here as well.
addons:
    apt:
        packages:
            - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
matrix:
    fast_finish: true
    include:
        - env: ARGS="" SKIP_DOCTESTS=false
        - env: ARGS="--resolver lts" SKIP_DOCTESTS=false
        - env: ARGS="--resolver nightly" SKIP_DOCTESTS=false
        - env: ARGS="--resolver lts-13" SKIP_DOCTESTS=false
        - env: ARGS="--resolver lts-12" SKIP_DOCTESTS=false

before_install:
    # Download and unpack the stack executable
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

    - stack $ARGS --no-terminal setup
    - stack $ARGS --no-terminal install hlint hscolour

script:
    - stack $ARGS --no-terminal build --pedantic

    # Tests
    - stack $ARGS --no-terminal test --pedantic :vgrep-test
    - $SKIP_DOCTESTS || stack $ARGS --no-terminal test --pedantic :doctest
    - stack $ARGS --no-terminal haddock --no-haddock-deps

    - stack $ARGS --no-terminal sdist
    - hlint src test app

# Caching so the next build will be fast too.
cache:
    directories:
        - $HOME/.stack
